### ISSUE TITLE
vendor/ is needed in excluded paths .codeclimate.yml

### ISSUE THREAD

**Issue by xgbuils** [coopdevs/katuma#107]
Hi!

In [code climate issues](https://codeclimate.com/github/coopdevs/katuma/issues) we can see issues related to `js` and `css` vendor libraries. It's needed to put `vendor/` in `.codeclimate.yml` to avoid that code climate analyze this kind of code.

**Comment by sauloperez** [comment]
See my comment https://github.com/coopdevs/katuma/pull/108#issuecomment-370684869
