### ISSUE TITLE
Double render error on #invitations/show action

### ISSUE THREAD

**Issue by andresgutgon** [coopdevs/katuma#78]
## WAT
This error:
```
AbstractController::DoubleRenderError (Render and/or redirect were called multiple times in this action. 
Please note that you may only call render OR redirect, and at most once per action. 
Also note that neither redirect nor render terminate execution of the action, 
so if you want to exit an action after redirecting, 
you need to do something like "redirect_to(...) and return".):
```

## How to reproduce?
Create an invitation and copy the URL from sent email. Something like this:
`http://localhost:8000/invitation/accept/Pj-Ut3Hh3azJYcQYDsc04Q1lXkQtza8mHEIih-z_hfg`
then paste on the browser. You must be already logged in katuma web
## The issue
If you are already logged in Katuma this code is returning that error :point_up: 
I think is here:
https://github.com/coopdevs/katuma/blob/develop/engines/onboarding/app/controllers/onboarding/api/v1/invitations_controller.rb#L64

**Comment by andresgutgon** [comment]
I did a PR. Let's discuss and if you want my idea we can close this issue

**Comment by enricostano** [comment]
Answered in the PR :+1:
