### ISSUE TITLE
Signup complete returns 404

### ISSUE THREAD

**Issue by andresgutgon** [coopdevs/katuma#80]
## WAT
This needs investigation. Maybe is a front end issue. But if I try to create a signup. 
```
/api/v1/signups/complete/TOKEN_HERE_PLEASE
```

The second time I POST the params I get a 404.

## Both requests
![image](https://cloud.githubusercontent.com/assets/49499/13204983/0a77cd4a-d8dd-11e5-94e7-6ec38b61da74.png)

**Comment by enricostano** [comment]
Maybe we delete the `Signup` even if something goes wrong during the first confirmation (`POST`)...

**Comment by enricostano** [comment]
Here is the pain point https://github.com/coopdevs/katuma/blob/develop/engines/account/app/services/account/signup_service.rb#L34

But it's wrapped in a transaction... so if the user already exists (for whatever reason) it should not delete the signup.

Worth investigating. Thanks @andresgutgon !

**Comment by andresgutgon** [comment]
old
